menu:
    博文: /
    归档: /archives/
    # 生活: /categories/live/
    # 读书: /categories/read/
    # 关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
# show_count: true
# favicon: https://github.com/dychf/dy_blog/blob/master/themes/hexo-theme-bubuzou/source/images/soccer.png?raw=true
# logo: https://github.com/dychf/dy_blog/blob/master/themes/hexo-theme-bubuzou/source/images/soccer.png?raw=true
# style: https://bubuzou.oss-cn-shenzhen.aliyuncs.com/blog/202010/bubuzou.css
favicon: ./images/soccer.png
logo: ./images/soccer.png
style: ./css/bubuzou.css

# Comment
#changyan: bubuzou
leancloud:
    appid: aD8jJBpu4oew3ovNY73z6Rdq-gzGzoHsz # 填写您的appid
    appkey: FdzS5SOPHdhYQoEUngQ8K2QW # 填写您的appkey
    comment: false # 是否开启评论系统
    timer: false # 是否开启文章统计


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2020

